### ISSUE TITLE
Depth normalization

### ISSUE THREAD

**Issue by KengChiLiu** [tum-vision/fusenet#13]
Hi @tum-vision @hazirbas 
In paper, it says the you normalize depth map to [0,255]
Does it mean to map 16bits [0,65535] to [0,255] or to map [min,max] of the depth map to [0,255] ?
By the way, did you  normalize too when only training with depth ?

Thank you

**Comment by KengChiLiu** [comment]
@hazirbas

**Comment by hazirbas** [comment]
Hey,
min,max to 0,255. But do the normalization on the depth values, D/1000.0, It might not look important however will definitely affect the scale.
