### ISSUE TITLE
How to process depth information ?

### ISSUE THREAD

**Issue by 15721130626** [tum-vision/fusenet#14]
hello
     I want to know how the depth channel pre-training model is generated, RGB channel and depth channel is called different pre-training model? Thanks.

**Comment by hazirbas** [comment]
Hi,
we initiliaze both branches with VGG16 weights. First layer in depth branch has 1-channel input, therefore we averaged the weights of the first convolutions in VGG16.

refer to [PyTorch](https://github.com/zanilzanzan/FuseNet_PyTorch) implementation.
