### ISSUE TITLE
How to calculate label weight?

### ISSUE THREAD

**Issue by charlesCXK** [tum-vision/fusenet#17]
Hi, I have a question about [label weight of NYU Depth V2](https://github.com/tum-vision/fusenet/blob/master/fusenet/data/nyuv2_40class_weight.txt). I can only calculate the distribution of each category in NYU Depth V2, how can I get the label weight from the distribution? Thank you!

**Comment by hazirbas** [comment]
Hi,
Please refer to Predicting Depth, Surface Normals and Semantic Labels with a Common Multi-Scale Convolutional Architecture, David Eigen, Rob Fergus

Weight is determined based on the frequency of the pixels and number of the images that that the category presents on.

**Comment by charlesCXK** [comment]
> Predicting Depth, Surface Normals and Semantic Labels with a Common Multi-Scale Convolutional Architecture

Thanks! That helps me a lot.
