### ISSUE TITLE
Problem about preparing LMDB

### ISSUE THREAD

**Issue by Teresa-Hu** [tum-vision/fusenet#2]
Hi.
Could you provide the document to prepare LMDB(./fusenet/scripts/save_lmdb.py)?Because the default caffe lmdb writer does not accept 4-D input image.
Thanks very much!

**Comment by shohan6** [comment]
Please provide the save_lmdb.py file for reference..

**Comment by hazirbas** [comment]
Hi @Teresa-Hu and @shohan6 ,

You could simply write an lmdb database in Python for 4D input and then use a split layer to unmerge the 4d input to 3d-1d in the prototxt.

[This link might help you](http://deepdish.io/2015/04/28/creating-lmdb-in-python/).
