### ISSUE TITLE
where is the code in script?

### ISSUE THREAD

**Issue by liu09114** [tum-vision/fusenet#3]
@SummerIcequeen @hazirbas 
I want to have a try with your codes, but I can't  find the code you referred in the README. The /fusenet/scripts/save_lmdb.py and ./fusenet/scripts/test_segmentation.py,  will you release the code, please?

**Comment by NikolausDemmel** [comment]
I'm not involved with this repository, not sure why you are pinging me.

**Comment by 9hgg** [comment]
Good evening @SummerIcequeen @hazirbas 
The following script  ./fusenet/scripts/test_segmentation.py is still not available. 
It would be interesting to know how you tested your algorithm, especially when you are resizing training images to 224x224 for training phase (as mentioned in the article)  but do you test at the same resolution or do you apply a resizing transformation ?
Hoping to hear from you,

Best regards,

Joris G.

**Comment by hazirbas** [comment]
Hey Joris,
Just resize the test images to 224x224 as well. Images with the bilinear and depth and label maps with the nearest neighbor interpolation.

Cheers,
Caner

**Comment by 9hgg** [comment]
Ok, thanks a lot !
Cheers,
Joris
