### ISSUE TITLE
Try to find save_lmdb.py

### ISSUE THREAD

**Issue by hehebloom** [tum-vision/fusenet#5]
Hi, I can not find a folder called script in fusenet as in description.
Is there any way I can find it?
Thank you.

**Comment by hazirbas** [comment]
Hi @hehebloom ,
It is currently not in the repository.

**Comment by manyaafonso** [comment]
The readme is extremely misleading if you are referring to scripts that are not included. Are you going to include these files in a future version?

**Comment by hazirbas** [comment]
We are working on it.

**Comment by hazirbas** [comment]
We are working on it.

**Comment by manyaafonso** [comment]
Thanks, looking forward to the new version.

**Comment by hazirbas** [comment]
Please refer to [PyTorch](https://github.com/zanilzanzan/FuseNet_PyTorch) implementation.
