### ISSUE TITLE
Problem about LMDB with C++

### ISSUE THREAD

**Issue by BenChenCh** [tum-vision/fusenet#7]
Hello,
     I am not sure whether this is the right way to create lmdb file to train fusenet:
      I created a program to convert images to lmdb  using c++ opencv. And I use the NYU dataset in SUNRGBD dataset. Firstly I load a rgb image file to a cv::Mat with 3 channels , load the corresponding depth file to a cv::mat with 1 channel(char) , create a label cv::Mat with 1 channel . By the way , all the cv::Mat has the same size. Then, I use the cv::merge function to merge all the three cv::Mat to a new cv::Mat with 5 channels. At last, I write it into lmdb file by converting the new cv::Mat to datum. 
      If that is the right way, I am faced up with another problem: how to find right value to fill the label cv:Mat ?  The way I use is to analyze the corresponding  index.json file of each rgb image and get an array of  polygon, then get x and y values of each element of polygon array to create 2D points. And then I get an area for each object using drawContours (opencv function) in a mask Mat which is created for each polygon array element . The value filling in the  area  of the mask is the index of the corresponding label order in classes.txt( which I use the 40 classes).At last I add all the masks to one mask which is the label cv::Mat for an image. Is that right?
           Hope for your response.

**Comment by hazirbas** [comment]
Hi,

I did not get your question. Label maps are provided in the benchmarks.

**Comment by BenChenCh** [comment]
Thanks so much!
