### ISSUE TITLE
about caffemodel

### ISSUE THREAD

**Issue by Mornyy** [tum-vision/fusenet#9]
Hi,
I have found the download_model_from_gist.sh in the "script" folder ,however I could not find the gist_id.
So I wonder if the caffemodels have been shared ? Or, where could I find the prototxt that discribes  the hyper-parameter ?
Thanks.

**Comment by hazirbas** [comment]
Hi,
No, we did not put the caffemodels online.

**Comment by Mornyy** [comment]
Ok, thanks for your reply ：）
